<a href="https://colab.research.google.com/github/kenichiy19/1CCPK-MLAM/blob/main/DATASET_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **DATASET 4 - Solar Power Generation Data (Kaggle)**

**Fonte**: https://www.kaggle.com/datasets/anikannal/solar-power-generation-data

**Situação**:

Uma equipe de operação de uma usina fotovoltaica deseja localizar períodos de alta geração e identificar quais inversores aparecem com maior frequência nesses momentos. Nesta atividade, o foco inicial será o arquivo de geração da planta, sem realizar junção com o arquivo de sensores.

## **Bibliotecas**

In [1]:
import pandas as pd

## **Código**

1. Apresente head(), shape, info() e describe().

In [2]:
df1 = pd.read_csv('/content/ENERGY_SAMPLE_DATA_TRATADA.csv')

In [3]:
df1.head()

,DATE_TIME,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD
0,10-06-2020 19:00,uHbuxQJl8lW7ozc,0.00,0.000,6645.000,7240508.000
1,28-05-2020 00:15,rGa61gmuvPhdLxV,0.00,0.000,0.000,7206549.000
2,17-05-2020 15:15,sjndEbLyjtCKgGv,7333.88,718.062,6442.000,7036055.000
3,01-06-2020 04:15,ih0vzX44oOqAx2f,0.00,0.000,0.000,6308232.000
4,17-05-2020 09:00,z9Y9gH1T5YWrNuG,7665.50,750.438,961.375,7021701.375

In [4]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13756 entries, 0 to 13755
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   DATE_TIME    13756 non-null  object
 1   SOURCE_KEY   13756 non-null  object
 2   DC_POWER     13756 non-null  float64
 3   AC_POWER     13756 non-null  float64
 4   DAILY_YIELD  13756 non-null  float64
 5   TOTAL_YIELD  13756 non-null  float64
dtypes: float64(4), object(2)
memory usage: 644.9+ KB

In [5]:
df1.describe()

           DC_POWER      AC_POWER   DAILY_YIELD   TOTAL_YIELD
count  13756.000000  13756.000000  13756.000000  1.375600e+04
mean    3135.848662    306.695495   3319.235216  6.978829e+06
std     4023.069619    393.124284   3142.249927  4.162164e+05
min        0.000000      0.000000      0.000000  6.183645e+06
25%        0.000000      0.000000      0.000000  6.509779e+06
50%      370.071500     35.771400   2730.425000  7.146218e+06
75%     6350.562500    622.065500   6293.782500  7.267996e+06
max    14416.100000   1405.590000   9163.000000  7.846821e+06

In [7]:
df1.columns

Index(['DATE_TIME', 'SOURCE_KEY', 'DC_POWER', 'AC_POWER', 'DAILY_YIELD',
       'TOTAL_YIELD'],
      dtype='object')

2. Carregue a amostra e renomeie as principais variáveis para nomes mais claros, como Potencia_CC, Potencia_CA e Geracao_Diaria.

In [12]:
df1.rename(columns={'DC_POWER': 'Potencia_CC',
                    'AC_POWER': 'Potencia_CA',
                    'DAILY_YIELD': 'Geracao_Diaria'
}, inplace=True)

In [13]:
df1.columns

Index(['DATE_TIME', 'SOURCE_KEY', 'Potencia_CC', 'Potencia_CA',
       'Geracao_Diaria', 'TOTAL_YIELD'],
      dtype='object')

3.	Determine a maior potência CA registrada.

In [16]:
maximo = df1['Potencia_CA'].max()
maximo

1405.59

4.	Calcule um limiar correspondente a 70% da potência CA máxima.

In [21]:
P_CA_70 = 0.70 * maximo

5.	Crie um DataFrame contendo somente registros acima desse limite e calcule sua quantidade e percentual.

In [27]:
df_alto = df1[df1['Potencia_CA'] > P_CA_70]

quantidade = len(df_alto)

percentual = len(df_alto) / len(df1) * 100

print(quantidade, percentual)

1185 8.614422797324805

6.	Utilize value_counts() em SOURCE_KEY dentro do DataFrame de alta geração.

In [35]:
contagem_inversores = df_alto['SOURCE_KEY'].value_counts() # Um dataframe com value_counts() somente com registros SOURCE_KEY foi criado.
print(contagem_inversores)

SOURCE_KEY
adLQvlD726eNBSB    68
McdE0feGgRqW7Ca    65
ZnxXDlPa8U1GXgE    63
pkci93gMrogZuBj    62
ZoEaEvLYb1n2sOq    61
1IF53ai7Xc0U56Y    59
YxYtjZvoooNbGkE    58
sjndEbLyjtCKgGv    57
z9Y9gH1T5YWrNuG    56
uHbuxQJl8lW7ozc    55
zVJPv84UY57bAof    54
zBIq5rxdHJRwDNY    53
ih0vzX44oOqAx2f    53
WRmjgnKYAwPKWDb    52
3PZuoBAID5Wc2HD    51
iCRJl6heRkivqQ3    51
VHMLBKoKgIrUVDU    51
wCURE6d3bPkepu2    49
rGa61gmuvPhdLxV    43
7JYdWkrLSPkdwr4    43
1BY6WEcLGh8j5v7    42
bvBOhCH3iADSZry    39
Name: count, dtype: int64

7.	Identifique qual inversor aparece com maior frequência nos registros de alta geração e descreva o que esse resultado permite observar, sem concluir desempenho ou falha apenas com esse recorte.

In [38]:
inversor_frequente = contagem_inversores.idxmax()
qtd_registros = contagem_inversores.max()
print(f"O inversor mais frequente é o '{inversor_frequente}' com {qtd_registros} registros.")

O inversor mais frequente é o 'adLQvlD726eNBSB' com 68 registros.

Este dado indica estritamente qual equipamento registrou o maior volume de amostras de tempo operando acima do limiar de 70% de potência. Mostra uma constância maior de operação em alta capacidade em relação aos demais.